// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'core/config/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQIGnyqumuwe0cPzbidXQUcLmQxmhFXY',
    appId: '1:289707656668:web:0948ff0e8eaa9a6aea7b19',
    messagingSenderId: '289707656668',
    projectId: 'putra-sport-hub',
    authDomain: 'putra-sport-hub.firebaseapp.com',
    storageBucket: 'putra-sport-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrnIC3WoxHYO6qlaPxlwJjvBjfyrUAP3U',
    appId: '1:289707656668:android:c852a5c9f5d0662eea7b19',
    messagingSenderId: '289707656668',
    projectId: 'putra-sport-hub',
    storageBucket: 'putra-sport-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJQAKnYvbkUufBpcZIIM49KiNGXmousiI',
    appId: '1:289707656668:ios:d4e9b737c0b57f22ea7b19',
    messagingSenderId: '289707656668',
    projectId: 'putra-sport-hub',
    storageBucket: 'putra-sport-hub.firebasestorage.app',
    iosBundleId: 'com.upm.putraSportHub',
  );
}

